Made this script somewhat safer.  It shouldn't delete source if there are problems during the run.

diff --git a/beautify b/beautify
--- a/beautify
+++ b/beautify
@@ -4,11 +4,18 @@
 #
 # http://astyle.sourceforge.net/
 ASTYLE=~/code/astyle/bin/astyle
+if [ ! -x $ASTYLE ] ; then
+    echo "Invalid image: $ASTYLE"
+    exit 1
+fi 
+
 for F in *.[ch] *.[ch]pp ; do
     if [ ! -e ${F}.orig ] ; then
 	echo Beautifying $F
-	mv ${F} ${F}.orig
-	$ASTYLE --style=ansi -BLaoy <${F}.orig | unexpand >${F}
+	mv ${F} ${F}.orig &&
+	$ASTYLE --style=ansi -BLaoy <${F}.orig | unexpand >${F}.new &&
+	mv ${F}.new ${F} ||
+	echo ERROR: Could not beautify $F
     else
 	echo "Skipping $F (remove ${F}.orig)"
     fi
